@startuml
skinparam BackgroundColorColor transparent
skinparam componentStyle rectangle
component View {
   component "Foundry" as Foundry {
   Hooks -down[hidden]- UserInteraction

      node Hooks{
         [Ready]
         [NewCombat]
         [EndCombat]
         [NewNPC]
         [DeleteNPC]
         [NextTurn]
      }
      node UserInteraction {
         [openJournal]
         [requestKnowledgeCheck]
         [RequestRoll]
         [updateNPC]
         [updateCombat]
         [changeTurn]
      }
      node SystemInteractions {
      [TODO]
      }
      }
      component moduleViews {
      node HUDInterface
      node PlayerJournal
      node GMJournal
   }
}
component Controller {
   node ActorControls {
      [getActor]
      [getEncounters]
      [updateNPC]
      [updateEncounters]
      }
   node JournalControls
   node PF2eSystemControls
   node PermissionManager
   node ViewControls
}

@enduml