@startuml
'https://plantuml.com/sequence-diagram

left to right direction
state InitializationHooks {
    OnReady --> GetEncounters
    GetEncounters --> GetNPC : Once Complete
    OnReady --> GetPlayerJournalBackup
    OnReady --> SetIcons
    OnReady --> GetSettings
    OnReady --> InitalizeHUD
    }

state CustomHooks {
   ClickIcon --> DrawPlayerJournal
   ClickIcon --> DrawGMJournal
   OnTokenSelect --> DrawHUD
   ClickHudIcon --> SendGMRequestDialogue

   OnUpdate: Actor --> UpdateActor
   OnUpdate: Encounter --> UpdateEncounter

   OnCheck: Success --> HighlightStat

   OnJournalUpdate: GMJournal --> UpdatePlayerJournal
   OnJournalUpdate: PlayerJournal --> UpdatePlayerJournal

   onRequest: HUDRequest --> SendGMRequestDialogue

   OnJournalUpdate --> UpdatePlayerJournal
   UpdatePlayerJournal --> UpdatePlayerJournalBackup : On Change

}

state LifeCycleHooks {
    CreateEncounter --> AddEncounter
    AddEncounter --> _GetNPC
    EndEncounter --> RemoveEncounter
}

@enduml